server {
    listen 80;

    # Backend API routes
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /internal/ {
        proxy_pass http://backend:8000/internal/;
        proxy_set_header Host $host;
    }
    location /auth/ {
        proxy_pass http://backend:8000/auth/;
        proxy_set_header Host $host;
    }
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
    }
    location /news {
        proxy_pass http://backend:8000/news;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /ads/ {
        proxy_pass http://backend:8000/ads/;
        proxy_set_header Host $host;
    }
    location /categories {
        proxy_pass http://backend:8000/categories;
        proxy_set_header Host $host;
    }
    location /docs {
        proxy_pass http://backend:8000/docs;
        proxy_set_header Host $host;
    }
    location /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
        proxy_set_header Host $host;
    }

    # Frontend
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
